### ISSUE TITLE
Self closing components not allowed ?

### ISSUE THREAD

**Issue by Jonarod** [developit/preact-markup#16]
When a `component` is used without children, like here:

```js
import Markup from 'preact-markup';

const Sidebar = ({ title }) => (
	<aside class="sidebar">
		<h2>{ title }</h2>
                <p>other stuff...</p>
	</aside>
);

let html = `
<h1>Hello, World</h1>
<sidebar title="My Sidebar!" />
<p>My paragraph</p>
`;
render(<Markup markup={html} components={{ Sidebar }} />, document.body);

// result is:
// Hello, World
// My Sidebar!
```

the `Sidebar` component is correctly rendered, but it trims down everything coming after, in this case: `<p>My paragraph</p>` is not printed.
I understand the `<sidebar />` self-closing tag does NOT play its role and captures everything coming after it as a `children` prop that is purposefully not displayed by my own component.

Closing the component the classic way `<my-component></my-component>` makes the trick, but I wonder what would be needed to let self-closing components to work ?

**Comment by TroyAlford** [comment]
This has to do with `preact-markup` using `DOMParser()` for parsing. The important code, in this case, is in https://github.com/developit/preact-markup/blob/master/src/parse-markup.js#L8-L26 - where the component chooses between a mime type of `text/html` or `application/xml`.

The short version is that both modes have quirks that are not ideal for parsing JSX (such as discarding all elements following a self-closing tag, auto-adding the closing tag, or erroneously treating `<link>` and `<Link>` as identical, by ignoring case-sensitivity).

Part of the goal of this lib, as I understand it, is to adhere to the importance of a tiny-footprint, like other `preact` modules - and it comes with certain tradeoffs.

If you _can_ ensure that your tags have closing nodes, that's the simple solution. If you _can't_ - and you also don't mind a _much_ larger file size - you can check out `react-jsx-parser` - which uses `Acorn` to parse (the same lib that `Babel` uses). (Full disclosure: I'm the author of that component)

For most purposes, I suggest `preact-markup` - because it's awesome and lightweight and small.

**Comment by Jonarod** [comment]
Thanks !

I could easily do it myself with a bit of regex like this:

```js
html_string.replace(/< *([^\s>]*)((?:(?!>)[\w\W])+?)\/ *>/g, '<$1$2></$1>');
```
This will basically create the self-closing tag automatically. 
If it finds something like `<mycomponent />`, it will match the string and replace it like by: `<mycomponent></mycomponent>`.

@developit let me know if this is of interest to you for a PR. Otherwise I consider it as a solution for users like me to do before submitting their `html` to `preact-markup`.
